- victron-venus-os-install.sh
Added quote for safety, exit values between 0 and 255.
> exit value and quotes introduced.

- data/etc/Spotmarket-Switcher/controller.sh
- data/etc/Spotmarket-Switcher/service/run
- victron-venus-os-install.sh
Thinking to have fixed most of the concerns of the shellcheck.
Please consider adding
```
DEBUG=1 LOG_FILE=/tmp/log.txt sh ./data/etc/Spotmarket-Switcher/controller.sh
```
as a test to the CI.
This commit will conflict with the other work on controller.sh - will address that later.
> Series of small shellcheck fixes and optical improvements.

- README.md
> Readme - asked chatGPT to help

- .github/workflows/main.yml
What we should add is to somehow run docker to execute the scripts in a Venus OS environment.
Well, let's see if this simple variant works :)
> Extending CI

- data/etc/Spotmarket-Switcher/controller.sh
- data/etc/Spotmarket-Switcher/service/run
- victron-venus-os-install.sh
Added --help to controller.sh and all the copyright statements can now be retrieved as a variable. This maybe something to also consider to add to the install script. Am shying away from it.
> Revisited copyright statements.

- .github/workflows/main.yml
- .github/workflows/venus.yml
> Extending CI with Venus OS in docker

- data/etc/Spotmarket-Switcher/controller.sh
- data/etc/Spotmarket-Switcher/service/run
- victron-venus-os-install.sh
Removed download of License and README file - which are not going anywhere during install.
> Harmless changes performed during docker preps

- victron-venus-os-install.sh
wget and curl are both not available, neither is opkg.
> Motivated by the failure in the victron docker environment

- victron-venus-os-install.sh
An oversight. Preparation of simplification of install script.
> Don't download install script in installer.

- .github/workflows/main.yml
This is a requirement for bug reports against shellcheck.
> Shellcheck version added to output

- .github/workflows/venus.yml
- scripts/controller.sh
> Reacting to shellcheck

- .github/workflows/main.yml
Motivated by my sudden "date -d"-Problem.
> Extending CI with MacOS

- release_notes.md
> release_notes.md - corrected syntax

- scripts/controller.sh
> Date on MacOS

- scripts/controller.sh
Also stating how long the delay will actually be.
> Wording in comments, whitespace.

- scripts/run
Reinstallation after Update should work again
> Redesign run script to fix installation issue

- victron-venus-os-install.sh
Ensure to add entry in a separate line
> victron-venus-os-install.sh fix

- scripts/config.txt
- scripts/controller.sh
Configuration has been moved to a separate file to make updates a little easier.
Code has been formatted a little more clearly
> Configuration outsourced

- .github/workflows/readme.yml
- README.cs.md
> Urgent fix, please update

- scripts/controller.sh
Script will stop if there is an API error
> Entso-E API optimization

- scripts/controller.sh
Entso-E API should work again now.
> Entso-E avoid empty line at extracted price file

- scripts/sample.config.txt
This pull request rewrites the configuration file. Making it easier to understand and improving on its structure.
> Rewrote the sample.config.txt adding more information and structure

- scripts/controller.sh
- scripts/sample.config.txt
Highlights:
- new config file format, thanks to @kLOsk 
- Correction of dynamic target-SOC calculation
- aWATTar API: Calculation of total prices including taxes
- Tibber API: Fallback to aWATTar API if next day prices are delayed
- Tibber API: Fallback to aWATTar API in case of Tibber API Error
> Release 2.4.6

- scripts/controller.sh
- scripts/sample.config.txt
please update. sonnenBatterie still needs some testing
> Venus OS MQTT syntax correction, added more logging, added experimental sonnenBatterie integration
